### ISSUE TITLE
[ORPJ-81] 설정 메뉴 개발

### ISSUE THREAD

**Issue by hurryduck** [orca-projects/bitdata-client#95]
### TODO
- 수집 페이지 (거래 데이터 수집 화면)
  - [ ] API 연동 확인
  - [ ] 설정 페이지, 거래내역 페이지 화면 이동
- 설정 페이지 개발
  - [ ] 회원 탈퇴 버튼 비활성화
